apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml
configurations:
  - nameReferences.yaml
images:
  - name: controller
    newName: ghcr.io/kubecfg/kubit
    newTag: v0.0.18@sha256:374dedb5e426dcb49c01b4d2ec976516f4d791cb48785cfaebb5444f1ac79ec6
