apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: influxdb

resources:
  - ../crd
  - ../namespace
  #- ../manager
  - ../rbac

patches:
  #- path: manager.yaml
  - path: role_binding.yaml
